# Generated by Django 5.1.4 on 2025-01-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='profile/'),
        ),
    ]
